Content:
    Zapdos:
        root_dir: ${ROOT_DIR}/doc/content
    moose:
        root_dir: ${MOOSE_DIR}/framework/doc/content
        content:
            - js/*
            - css/*
            - contrib/**
            - media/**
            - templates/stubs/*

Renderer:
    type: MooseDocs.base.MaterializeRenderer
    name: Zapdos

Extensions:
    MooseDocs.extensions.navigation:
        name: 'Zapdos'
        repo: https://github.com/shannon-lab/zapdos
        menu:
            Getting Started: getting_started/index.md
            Documentation: documentation.menu.md
            Help: help.menu.md
            Citing: citing.md
    MooseDocs.extensions.template:
        active: True
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        includes:
            - include
